Multiweb/urls.py
from django.contrib import admin
from django.urls import include,path
from multierp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('multierp', views.index, name='index'),
    path('admin/', admin.site.urls,name=admin),
    path('multierp/', include('multierp.urls')),
]

multierp/urls.py
from django.urls import include,path

from . import views

app_name='multierp'
urlpatterns = [
    path('login', views.loginreq, name='login_req'),
    path('logout', views.logoutreq, name='logout_req'),
    #path('register', views.register, name='register'),


    #------------------ HOMEPAGE -----------------
    path('homepage',views.homepage,name='homepage'),

    #====================== SALES ORDER ============================

    #------------ SALES ORDER PAGE------------------
    path('salesorderpage', views.salesorderpage, name='salesorderpage'),
    
    #------------ Create order ------------
    path('createsalesorder', views.createSalesOrder, name="createsalesorder"),
   
    #------------ Update order ------------
    path('updatesalesorder/<str:pk>/', views.updateSalesOrder, name="updatesalesorder"),

    #------------ Delete order ------------
    path('deletesalesorder/<str:pk>/', views.deleteSalesOrder, name="deletesalesorder"),

    #------------------------ Sales Order Details -------------------------
    path('salesorderdetails/<str:pk>', views.salesorderDetails, name="salesorderdetails"),

    #====================== PURCHASE ORDER ============================

    #------------ Purchase order page ------------------
    path('purchaseorderpage', views.purchaseorderpage, name='purchaseorderpage'),
    
    #------------ Create order ------------
    path('createpurchaseorder', views.createPurchaseOrder, name="createpurchaseorder"),
   
    #------------ Update order ------------
    path('updatepurchaseorder/<str:pk>/', views.updatePurchaseOrder, name="updatepurchaseorder"),

    #------------ Delete order ------------
    path('deletepurchaseorder/<str:pk>/', views.deletePurchaseOrder, name="deletepurchaseorder"),

    #------------------------ Purchase Order Details -------------------------
    path('purchaseorderdetails/<str:pk>', views.purchaseorderDetails, name="purchaseorderdetails"),

    #==================================================================

    #======================= Items =================================

    #----------------------- Item Page -------------------------------
    path('itempage', views.itemPage, name='itempage'),   
    
    #----------------------- Create Item -----------------------------
    path('createitem', views.createItem, name='createitem'),

    #----------------------- Delete Item -----------------------------
    path('deleteitem/<str:pk>/', views.deleteItem, name="deleteitem"),

    #----------------------- Update Item -----------------------------
    path('updateitem/<str:pk>/', views.updateItem, name="updateitem"),

    #----------------------- Details Item -----------------------------
    path('itemdetails/<str:pk>/', views.itemDetails, name="itemdetails"),

    #================================================================

    #========================== Party ==============================
    
    #------------------------ Party Page ------------------------
    path("partypage",views.partypage,name="partypage"),
    
    #------------------------ Create Party ----------------------
    path('create_party', views.createParty, name='createparty'),

    #------------------------ Update Party ----------------------
    path('updateparty/<str:pk>/', views.updateParty, name="updateparty"),

    #------------------------ Delete Party ----------------------
    path('deleteparty/<str:pk>/', views.deleteParty, name="deleteparty"),
    
    #------------------------ Party Details ----------------------
    path('partydetails/<str:pk>', views.partyDetails, name="partydetails")
    #=========================================================================

]

multierp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,authenticate,logout
from django.template import loader
from django.urls import reverse
from django import forms
from .form import *
from django.db.models import Q
from django.contrib import messages
from .filters import *
from django.contrib.auth.decorators import permission_required

from .models import *

# ===================================== HomePage =========================

def homepage(request):
	return render(request,'multierp/homepage.html')

#---------------------- welcome page --------------------

def index(request):
	return render(request = request,
				  template_name = "multierp/index.html",)

# ==================================== Order ===========================

# ============================== Purchase Order =====================================

def purchaseorderpage(request):
	orders = PurchaseOrder.objects.all()
	total_orders = PurchaseOrder.objects.all().count()
	delivered = PurchaseOrder.objects.filter(Status='Closed').count()
	pending = PurchaseOrder.objects.filter(~Q(Status ='Closed')).count()

	orderFilter = PurchaseOrderFilter(request.GET, queryset=orders) 
	searchpurchaseorders = orderFilter.qs

	context = {'orders':orders,'total_orders':total_orders, 'delivered':delivered, 'pending':pending, 'filter':orderFilter,'searchpurchaseorders':searchpurchaseorders}
	return render(request, 'multierp/purchaseorderpage.html', context)

#-------------------- create purchase order -------------------
def createPurchaseOrder(request):
	action='Create'
	form = CreatePurchaseOrderForm()
	if request.method == 'POST':
		form = CreatePurchaseOrderForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('purchaseorderpage')
	context =  {'form':form,'action':action}
	return render(request, 'multierp/createpurchaseorder.html', context)


#------------------ Delete Purchase Order --------------------
def deletePurchaseOrder(request, pk):
	order = PurchaseOrder.objects.get(id=pk)
	if request.method == 'POST':
		order.delete()
		return redirect('multierp:purchaseorderpage')
		
	return render(request, 'multierp/delete_item.html', {'item':order})	

#------------------- Update Purchase Order ------------------
def updatePurchaseOrder(request,pk):
	action='Update'
	order = PurchaseOrder.objects.get(id=pk)
	form = UpdatePurchaseOrderForm(instance=order)	
	if request.method == "POST":
		form = UpdatePurchaseOrderForm(request.POST, instance=order)
		if form.is_valid():
			form.save()
			return redirect('multierp:purchaseorderpage')
	return render(request, 'multierp/createpurchaseorder.html',{"form":form,"action":action})

#-------------------------- Purchase Order Details ---------------------
def purchaseorderDetails(request,pk):
	order = PurchaseOrder.objects.get(pk=pk)
	context = {'order':order}
	return render(request, 'multierp/purchaseorderdetails.html',context)


#==================================================================================================

#-------------------- sales order Page --------------------

def salesorderpage(request):
	orders = SalesOrder.objects.all()
	total_orders = SalesOrder.objects.all().count()
	delivered = SalesOrder.objects.filter(Status='Closed').count()
	pending = SalesOrder.objects.filter(~Q(Status ='Closed')).count()

	orderFilter = SalesOrderFilter(request.GET, queryset=orders) 
	searchorders = orderFilter.qs

	context = {'orders':orders,'total_orders':total_orders, 'delivered':delivered, 'pending':pending, 'filter':orderFilter, 'searchorders':searchorders}
	return render(request, 'multierp/salesorderpage.html', context)


#------------------ Create Order --------------------

def createSalesOrder(request):
	action='Create'
	form = CreateSalesOrderForm()
	if request.method == 'POST':
		form = CreateSalesOrderForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('salesorderpage')

	context =  {'form':form,"action":action}
	return render(request, 'multierp/createsalesorder.html', context)



#------------------ Delete Order --------------------
def deleteSalesOrder(request, pk):
	order = SalesOrder.objects.get(id=pk)
	if request.method == 'POST':
		order.delete()
		return redirect('multierp:salesorderpage')
		
	return render(request, 'multierp/delete_item.html', {'item':order})	


#--------------------- Update Sales Order ------------------
def updateSalesOrder(request,pk):
	action='Update'
	order = SalesOrder.objects.get(id=pk)
	form = UpdateSalesOrderForm(instance=order)
	if request.method == "POST":
		form = UpdateSalesOrderForm(request.POST, instance=order)
		if form.is_valid():
			form.save()
			return redirect('multierp:salesorderpage')
	return render(request, 'multierp/createsalesorder.html',{"form":form,"action":action})

#-------------------------- Sales Order Details ---------------------
def salesorderDetails(request,pk):
	order = SalesOrder.objects.get(pk=pk)
	context = {'order':order}
	return render(request, 'multierp/salesorderdetails.html',context)


# --------------------- Logout --------------------------
def logoutreq(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("multierp:login_req")



#-------------------- Login ------------------------
def loginreq(request):
	form = AuthenticationForm()
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)

		if user is not None:
			 login(request, user) 
			 return HttpResponseRedirect('homepage')
	return render(request = request,
				  template_name = "multierp/login.html",
				  context={'form':form})

#------------------------ Register ---------------------

def register(request):
	form = SignUpForm()
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
	return render(request = request,
					template_name = "multierp/register.html",
					context={"form":form})

	#----------------- Notification ------------------

"""def notifications(request):
	action="create"
	notifications = Notification.objects.all()
	context = {'notifications': notifications,'action':action}

	return render(request, 'multierp/notifications.html', context)"""

#=============================== Item ======================================

# ----------------------- ItemPage --------------------------

def itemPage(request):
	items = Item.objects.all()
	total_items = items.count()
	latest_items = items.order_by('-item_date')[0:5]

	itemFilter = ItemFilter(request.GET, queryset=items)
	searchitems = itemFilter.qs

	context = {"total_items":total_items,"latest_items":latest_items,"filter":itemFilter,"items":items,"searchitems":searchitems}
	return render(request, 'multierp/itempage.html', context)

#------------------------- Create Item ------------------

#@permission_required('multierp:add_item')
def createItem(request):
	action= "Create"
	form = CreateItemForm()
	if request.method == "POST":
		form=CreateItemForm(request.POST)
		if form.is_valid:
			form.save()
		return HttpResponseRedirect('itempage')
	
	context = {'form':form,"action":action}
	return render(request, 'multierp/create_item.html', context)

def deleteItem(request,pk):
	item = Item.objects.get(pk=pk)
	if request.method == 'POST':
		item.delete()
		return redirect('multierp:itempage')
	return render(request, 'multierp/delete_item.html',{"item":item})	

def updateItem(request,pk):
	action= "Update"
	item = Item.objects.get(pk=pk)
	form = UpdateItemForm(instance=item)
	if request.method == "POST":
		form = UpdateItemForm(request.POST, instance=item)
		if form.is_valid():
			form.save()
			return redirect('multierp:itempage')
	return render(request, 'multierp/create_item.html',{"form":form,"action":action})
	
def itemDetails(request,pk):
	item = Item.objects.get(pk=pk)
	context = {'item':item}
	return render(request, 'multierp/itemdetails.html',context)

#=================================== PARTY ================================

#------------------- Create Party -------------------------

def createParty(request):
	action='Create'
	form = CreatePartyForm()
	if request.method == "POST":
		form=CreatePartyForm(request.POST)
		if form.is_valid:
			form.save()
		return HttpResponseRedirect('partypage')
	
	context = {'form':form,"action":action}
	return render(request, 'multierp/create_party.html',context)

def partypage(request):
	if request.method == 'GET':
		party= Party.objects.all()
	else:
		party= Party.objects.none()
	partycount = party.count()
	latest_party = Party.objects.all().order_by('-Party_Date')[0:5]

	itemParty=PartyFilter(request.GET, queryset=party)
	searchparty = itemParty.qs

	context={"partycount":partycount,"party":party,"filter":itemParty,"searchparty":searchparty,'latest_party':latest_party}
	return render(request, 'multierp/partypage.html',context)

def deleteParty(request, pk):
	party = Party.objects.get(id=pk)
	if request.method == 'POST':
		party.delete()
		return redirect('multierp:partypage')
	return render(request, 'multierp/delete_item.html',{"item":party})	

def updateParty(request,pk):
	action='Update'
	party = Party.objects.get(id=pk)
	form = UpdatePartyForm(instance=party)
	if request.method == "POST":
		form = UpdatePartyForm(request.POST, instance=party)
		if form.is_valid():
			form.save()
			return redirect('multierp:partypage')
	return render(request, 'multierp/create_party.html',{"form":form,"action":action})


templates/multierp/create_item.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}

{% include 'multierp/header.html' %}

<h1>{{action}} Item</h1>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{% for field in form %}
					{{field.label}}
					{{field|add_class:'form-control'}}	
				{% endfor %}
				<hr>
				<input type="submit" class="btn btn-info">
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/multierp/createpurchaseorder.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}

{% include 'multierp/header.html' %}

<h1>{{action}} Purchase Order</h1>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{% for field in form %}
					{{field.label}}
					{{field|add_class:'form-control'}}	
				{% endfor %}
				<hr>
				<input type="submit" class="btn btn-info">
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/multierp/createsalesorder.html
{% extends 'base.html' %}
{% block content %}
{% load widget_tweaks %}

{% include 'multierp/header.html' %}



<h1>{{action}} Sales Order</h1>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
			<form action="" method="POST">
				{% csrf_token %}
				{% for field in form %}
					{{field.label}}
					{{field|add_class:'form-control'}}	
				{% endfor %}
				<hr>
				<input type="submit" class="btn btn-info">
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/multierp/delete_item.html
{% extends 'base.html' %}
{% block content %}

{% include 'multierp/header.html' %}
<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">
			<p>Are you sure you want to delete ?</p>
			<form  action="" method="post">
				{% csrf_token %}
				<a class="btn btn-warning" href="{{request.META.HTTP_REFERER}}">Go back</a>

			  	<input class="btn btn-danger" type="submit"/>
			</form>
		</div>
	</div>
</div>


{% endblock content %}

templates/multierp/detail.html
{% extends 'base.html' %}
{% include 'multierp/header.html' %}

{% block content %}

{% include 'multierp/header.html' %}
<hr>
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Product</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.product }}</h3>
			  	</div>
			</div>
		</div>
    </div>
    
    <div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Company</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.company }}</h3>
			  	</div>
			</div>
		</div>
	</div>
	
	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Date order was created</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.date_created }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Current Status</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.status}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>
	
<div class="row">
    <div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Sales Registered By</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.sales_registration }}</h3>
			  	</div>
			</div>
		</div>
    </div>
    
    <div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Operation Status Changed By</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.operation_handler }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Finance Status Changed By</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.finance_handler }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Shipping Status Changed By</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ order.shipping_handler }}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

templates/multierp/homepage.html
{% extends 'base.html' %}

{% block content %}
<div style="text-align:center;">
    <h1>Multidimensions</h1>
    <h5>Friction Management People</h5>

    <div class="row" style="margin-top: 1rem; position: relative;">
        <div class="col">
            <div class="card" style="width:80%">
                <div class="card-body" border:2px>
                <h5 class="card-title">Item</h5>
                <a class="btn btn-primary" href="{% url 'multierp:itempage' %}">Item</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width:80%">
                <div class="card-body">
                <h5 class="card-title">Order</h5>
                <a class="btn btn-primary" href="{% url 'multierp:salesorderpage' %}">Sales Order</a>
                <a class="btn btn-primary" href="{% url 'multierp:purchaseorderpage' %}">Purchase Order</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width:80%">
                <div class="card-body">
                <h5 class="card-title">Party</h5>
                    <a class="btn btn-primary" href="{% url 'multierp:partypage' %}">Party</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/multierp/invalid_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1 id="test">Testing </h1>        
    </div>
{% endblock %}

templates/multierp/purchaseorderpage.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
    Accounts page
{% endblock %}

{% block content %}
{% include 'multierp/header.html' %}
<br>
<h1 style="text-align: center;">Purchase Order</h1>
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-success text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white bg-danger mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col">
		<div class="card card-body border-0">
			<form method="get">
		    {% for field in filter.form %}
		    	{{field.label}}
				{{field|add_class:'form-control-sm'}}
				&nbsp;&nbsp;&nbsp;&nbsp;
			{% endfor %}
			<br>
			<br>
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
</div>

<div class="col-md-12">
	<h5>Search Result</h5>
	<div class="card card-body">					
		<table class="table table-sm" border="2px">
			<tr>
				<th>Product</th>
				<th>Date Orderd</th>
				<th>Status</th>
				{% if perms.multierp.change_purchaseorder %}
					<th>Update</th>
				{% endif %}
				{% if perms.multierp.delete_purchaseorder %}
					<th>Remove</th>
				{% endif %}
				<th>Details</th>
			</tr>
			{% for order in searchpurchaseorders %}
				<tr>
					<td>{{order.PO_no}}</td>
					<td>{{order.PO_Date}}</td>	
					<td>{{order.Status}}</td>
					<td><a class="btn btn-sm btn-warning" href="{% url 'multierp:updatepurchaseorder' order.id %}">Update</a></td>
					<td><a class="btn btn-sm btn-danger" href="{% url 'multierp:deletepurchaseorder' order.id %}">Cancel</a></td>
					<td><a class="btn btn-sm btn-primary" href="{% url 'multierp:purchaseorderdetails' order.id%}">Details</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>


<div class="col-md-12">
	<h5>Latest 5 Orders</h5>
	<div class="card card-body">	
		{% if perms.multierp.add_purchaseorder %}
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'multierp:createpurchaseorder' %}">Create Purchase Order</a>
		{% endif %}
		<table class="table table-sm" border="2px">
			<tr>
				<th>Product</th>
				<th>Date Orderd</th>
				<th>Status</th>
				<th>Update</th>
				<th>Remove</th>
				<th>Details</th>
			</tr>
			{% for order in orders %}
				<tr>
					<td>{{order.PO_no}}</td>
					<td>{{order.PO_Date}}</td>	
					<td>{{order.Status}}</td>
					<td><a class="btn btn-sm btn-warning" href="{% url 'multierp:updatepurchaseorder' order.id %}">Update</a></td>
					<td><a class="btn btn-sm btn-danger" href="{% url 'multierp:deletepurchaseorder' order.id %}">Cancel</a></td>
					<td><a class="btn btn-sm btn-primary" href="{% url 'multierp:purchaseorderdetails' order.id%}">Details</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>



{% endblock content %}

templates/multierp/salesorderpage.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
    Sales Order page
{% endblock %}

{% block content %}
{% include 'multierp/header.html' %}
<br>

<h1 style="text-align: center;">Sales Order Page</h1>
<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-info text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{total_orders}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center bg-success text-white  mb-3" >
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{delivered}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white bg-danger mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{pending}}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>


<div class="row">
	<div class="col">
		<div class="card card-body border-0">
			<form method="get">
		    {% for field in filter.form %}
		    	{{field.label}}
				{{field|add_class:'form-control-sm'}}
				&nbsp;&nbsp;&nbsp;&nbsp;
			{% endfor %}
			<br>
			<br>
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
</div>

<div class="col-md-12">
	<h5>Search Results</h5>
	<div class="card card-body">
		<table class="table table-sm" border="2px">
			<tr>
				<th>Product</th>
				<th>Date Orderd</th>
				<th>Status</th>
				{% if perms.multierp.change_salesorder %}
					<th>Update</th>
				{% endif %}				
				{% if perms.multierp.delete_salesorder %}
					<th>Remove</th>
				{% endif %}
				<th>Details</th>
			</tr>
			{% for order in orders %}
				<tr>
					<td>{{order.SO_no}}</td>
					<td>{{order.SO_Date}}</td>	
					<td>{{order.Status}}</td>
					{% if perms.multierp.change_salesorder %}
						<td><a class="btn btn-sm btn-warning" href="{% url 'multierp:updatesalesorder' order.id %}">Update</a></td>
					{% endif %}
					{% if perms.multierp.delete_salesorder %}
						<td><a class="btn btn-sm btn-danger" href="{% url 'multierp:deletesalesorder' order.id %}">Cancel</a></td>
					{% endif %}					
					<td><a class="btn btn-sm btn-primary" href="{% url 'multierp:salesorderdetails' order.id %}">Details</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>



<div class="col-md-12">
	<h5>Latest Orders</h5>
	<div class="card card-body">
		{% if perms.multierp.add_salesorder %}
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'multierp:createsalesorder' %}">Create Sales Order</a>
		{% endif %}
		<table class="table table-sm" border="2px">
			<tr>
				<th>Product</th>
				<th>Date Orderd</th>
				<th>Status</th>
				{% if perms.multierp.change_salesorder %}
					<th>Update</th>
				{% endif %}				
				{% if perms.multierp.delete_salesorder %}
					<th>Remove</th>
				{% endif %}
				<th>Details</th>
			</tr>
			{% for order in orders %}
				<tr>
					<td>{{order.SO_no}}</td>
					<td>{{order.SO_Date}}</td>	
					<td>{{order.Status}}</td>
					{% if perms.multierp.change_salesorder %}
						<td><a class="btn btn-sm btn-warning" href="{% url 'multierp:updatesalesorder' order.id %}">Update</a></td>
					{% endif %}
					{% if perms.multierp.delete_salesorder %}
						<td><a class="btn btn-sm btn-danger" href="{% url 'multierp:deletesalesorder' order.id %}">Cancel</a></td>
					{% endif %}					
					<td><a class="btn btn-sm btn-primary" href="{% url 'multierp:salesorderdetails' order.id %}">Details</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>

{% endblock content %}